### ISSUE TITLE
Version 2.0.16.50 has problems with disabled versions

### ISSUE THREAD

**Issue by TheDutchJewel** [hartenthaler/hh_extended_family#102]
It seems that version 2.0.16.50 has problems with disabled versions.

I normally disable the previous version by naming it (like `hh_extended_family-2.0.16.49.disable`), and copy the new one to `hh_extended_family`. But the new version apparently has a problem with this and seems to use the old version.

Only by deleting the old version does the new one work properly: the issues [#95](https://github.com/hartenthaler/hh_extended_family/issues/95), [#94](https://github.com/hartenthaler/hh_extended_family/issues/94) and [#97](https://github.com/hartenthaler/hh_extended_family/issues/97) are fixed!

**Comment by reteP-riS** [comment]
> It seems that version 2.0.16.50 has problems with disabled versions.
> 
> I normally disable the previous version by naming it (like `hh_extended_family-2.0.16.49.disable`), and copy the new one to `hh_extended_family`. But the new version apparently has a problem with this and seems to use the old version.

I can confirm this behaviour. I renamed the old version folder to ./modules_v4/hh_extended_family-2.0.16.49 and installed version 50 into a ./modules_v4/hh_extended_family folder. Because I am using opcache I can see that in the opcache folder 2 corresponding subfolders ./opcache/hh_extended_family and ./opcache/hh_extended_family-2.0.16.49 have been created with a duplicate autoload.php.bin and several other binaries inside them - and these binaries were even recreated after deleting all of them.

./hh_extended_family:
autoload.php.bin
module.php.bin
./hh_extended_family-2.0.16.49:
resources ( a folder including the lang and views subfolders, etc.)
autoload.php.bin
ExtendedFamily.php.bin
ExtendedFamilyTabModule.php.bin

It seems to me that several files from the old version are being used. I then tested it from a different browser only to find out that the issue persists and most probably is not related to browser features or cookies. I conclude it is either server or code related.

After deleting the ./modules_v4/hh_extended_family-2.0.16.49 folder (and all the opcache folders) everything works as expected. The opcache creates an ./opcache/hh_extended_family folder only and the mother in law shows up.

**Comment by hartenthaler** [comment]
I will remove the newly introduced autoload feature, which I don't understand fully. It seems that this has side effects.

**Comment by hartenthaler** [comment]
It is a good idea to disable/rename old versions and not overwrite them with a new version, as I did up to now. This will allow me to reactivate them very easily.

@TheDutchJewel and @reteP-riS: can you check if the new release 2.0.16.51 solves this issue, please?

**Comment by TheDutchJewel** [comment]
Yes, this is fixed: I've disabled v2.0.16.49 and still see the new INFANT/STILLBORN labels.
