### ISSUE TITLE
v2.0.16.52 - Error with any indivual page in webtrees

### ISSUE THREAD

**Issue by TheDutchJewel** [hartenthaler/hh_extended_family#105]
Now the preferences page can be opened, but every time I try to open an individual tab in webtrees, I get the following message:

![afbeelding](https://user-images.githubusercontent.com/46184729/133315920-c410de1c-a278-431d-a7fc-ffd36a464142.png)

**Comment by yako1984** [comment]
Install the x.48, the others are testing and failing. the latest version also gives me an error and does not work well. But the creator also has to rest, that his head is going to explode.

**Comment by hartenthaler** [comment]
this is already solved by release 2.0.16.53

Thank you for your patience. Performance bugs are much more complicated than other bugs. And I cannot test it, because I don't see a problem with my own installation. Maybe release 53 brings more insights. And tomorrow will be a new day with a fresh brain!

**Comment by TheDutchJewel** [comment]
Thank you Hermann!
