### ISSUE TITLE
Czech Translations

### ISSUE THREAD

**Issue by jpretired** [hartenthaler/hh_extended_family#28]
The attached file contains the Czech translations into module.php.
[function-czechtranslations.txt](https://github.com/hartenthaler/hh_extended_family/files/6669409/function-czechtranslations.txt)

**Comment by hartenthaler** [comment]
@jpretired Thank you very much!

regarding partners/spouses: after discussion with TheDutchJuwel spouses was replaced by partners (and husband by male partner, ...) because this is more general and because this extended family part contains partners of partners, too.

Maybe you like to adjust your translation, too.

**Comment by jpretired** [comment]
Amended Czech translations as to the above comment:
[function-czechtranslations.txt](https://github.com/hartenthaler/hh_extended_family/files/6670361/function-czechtranslations.txt)

**Comment by hartenthaler** [comment]
will be part of next release

Thank you very much!
