### ISSUE TITLE
Questionable: 2 fathers because mother had 2 partnerships?

### ISSUE THREAD

**Issue by reteP-riS** [hartenthaler/hh_extended_family#34]
In my dataset I have an illigetimate son John (I3) where the extended family tab **correctly** says "John has **2 fathers** and 1 mother recorded". John's father was the first and unmarried partner (I1) of John's mother (I2). A few years later his mother (I2) married a different man and this husband (I4) adopted the illigetimate John (I3). Then the married couple had a legitimate son David (I5) and the two sons John and David were brothers - not stepbrothers. So far so good.

The extended family tab for the legitimate son David (I5) now **incorrectly** says "David has **2 fathers** and 1 mother recorded" as well. John (I3) and David (I5) share the same mother, but I don't see why the illegitimate father (I1) of John (I3) should be shown as father of David (I5).

Summary: John had both a biological father and an adoptive father. But David had only one father, i. e. his biological father. John's father was by no means somehow related to David, neither as biological father, nor as stepfather, nor as adoptive father.

I know this is a complex family situation, but I consider the current representation for David as incorrect. What do you think?

**Comment by hartenthaler** [comment]
You know that John's father I1 has no relation to David.

But let us assume that John's mother I2 was married first(!) with I4 and they got their son David. Then the mother married I1 (because I4 died or they were divorced) and this couple got their son John. Again John and David are half-brothers. Now I1 is the stepfather of David. It is totally symmetric with the mother in the center. If you draw schematics you cannot see any difference between your scenario and mine.

For me John's father I1 is a (potential) step-parent of David. I do not plan to check living dates and events like divorce/marriage and so on to decide if someone was a potential step-parent or a real step-parent.

It is the extended family! They all (I1 to I5) are members of this extended patchwork family. Maybe not all at the same time, maybe not practicing this membership (because I1 was maybe only a member nine months before John was born, but who knows?

**Comment by reteP-riS** [comment]
Thanks for your sharing your view, Hermann. I can live with that approach although in rare situations it might cause some questions.

**Comment by hartenthaler** [comment]
To raise such questions is one of the tasks of this module! It should help to make (potential) connections visible that we maybe have not seen before in the way the relationships were presented by already existing modules of webtrees. I hope that this is the added value of this module.

**Comment by hartenthaler** [comment]
Maybe if such a question was raised when looking at the disturbing results of this module, you can decide to document that these five persons lived at the same place for many years together in a patchwork family or you decide to document explicitly that I1 was a biological father but was never ever seen in the family after the birth of John.
