### ISSUE TITLE
Proposal: change sequence of family parts

### ISSUE THREAD

**Issue by reteP-riS** [hartenthaler/hh_extended_family#35]
Hermann, this is a great module and I wouldn't bother you if it weren't. I know there exist many solutions, but may I suggest to change the sequence of the relationships as follows:

PROPOSAL 1:
- Grandparents
- Parents
- Uncles and Aunts (because these are the brothers and sisters of the parents above)
- Cousins (because these are the children of the uncles and aunts above)
- Siblings
- Nephews and Nieces (because these are the children of the siblings above)
- Partners
- Children
- Grandchildren

PROPOSAL 2:
- Grandparents
- Parents
- Siblings
- Partners
- Children
- Grandchildren
- Nephews and Nieces (sidelines, 1 step up 2 steps down)
- Uncles and Aunts (sidelines, 2 steps up 1 step down)
- Cousins (sidelines, 2 steps up 2 steps down, children of the above uncles and aunts)

Please feel free to reject my proposal without explanation in case you feel you already have the best solution.

**Comment by hartenthaler** [comment]
I had the idea to make the sorting flexible, too. At the moment sorting follows the generations: Grandparents = +2 parents /uncles/aunts = +1, siblings, partners, cousins = 0, children, nephews, nieces = -1, grandchildren = -2.

At the moment the sequence of all family parts is hardcoded, but the parts are very similar so that it would be possible to have a loop around one generic part and some minor if/then/else. I will do it, but it will need some time.

**Comment by reteP-riS** [comment]
Thanks for your reply. I now understand the sequence you have chosen and I admit it makes perfect sense (as well). So don't worry. Anyway, thanks for considering my comments.

**Comment by hartenthaler** [comment]
@reteP-riS: this is now implemented with release 2.0.16.26

**Comment by reteP-riS** [comment]
Thank you, Hermann!
