### ISSUE TITLE
2.0.16.31 - Partner section: a correct and incorrect summary if probands partner has/had a partner

### ISSUE THREAD

**Issue by TheDutchJewel** [hartenthaler/hh_extended_family#56]
For a proband whose partner has/had a partner, two summaries appear:
1. a correct statement of the number of partners and partners of partners
2. an incorrect one in which the partner of the partner is stated as the partner of the proband

![afbeelding](https://user-images.githubusercontent.com/46184729/126102371-df9606d9-8d23-4197-80e2-dc642ceeade4.png)

**Comment by hartenthaler** [comment]
Thank you for your comment. Concluding from that you do not comment on the grouping of the partners, I assume that this is now fine for you.

For me, both statements are correct, because for me "partner" includes direct partners and partners of partners. I plan to combine both statements to one statement: "xxx has two female partners and 1 male partner of partners.", but yesterday it was too late to program this.

**Comment by TheDutchJewel** [comment]
>I plan to combine both statements to one statement: "xxx has two female partners and 1 male partner of partners."

That's a fine summary!

**Comment by reteP-riS** [comment]
I usually urge to make design decisions instead of implementing too many options, but in this specific case I am not convinced that the partner's partner should be shown at all and I'd therefore like to ask whether this can be implemented with an on/off switch in the admin area.

**Comment by hartenthaler** [comment]
Now the statement combines information about partner versus partner of partners and male versus female.

Partners of partners are shown in the webtrees standard "information bar", too. So why should they be hidden in the extended family module? For me, they are members of the extended family.
