### ISSUE TITLE
v2.0.16.33 shows adopted child/sibling as biological child/sibling

### ISSUE THREAD

**Issue by reteP-riS** [hartenthaler/hh_extended_family#65]
This is related to the specific situation I described in [issue 34](https://github.com/hartenthaler/hh_extended_family/issues/34) and other similar issues referring to a partner's partner and their offsprings.

It seems with the latest version v2.0.16.33 the revised headline _biological_ children lists the adopted son John now incorrectly as biological son.

Is this issue related to [issue 59](https://github.com/hartenthaler/hh_extended_family/issues/59) for half-siblings and step-siblings or is it a different one?

**Comment by hartenthaler** [comment]
Legally this is correct because adopted children are equal to biological children. But I should be more precise. In earlier versions of this module a person was marked with "adopted", but I had a problem with this and deactivated it temporarily. I have to reactivate this label now again.
Issue #59 will be solved in the next release, but this is independent of this new issue.

**Comment by hartenthaler** [comment]
This bug is also relevant for adoptive siblings / children / parents and it is related to #6 . I will close #6 and keep this one open.

**Comment by reteP-riS** [comment]
I understand this is a rather complex topic and appreciate your drive to resolve this very much. Kudos!

**Comment by hartenthaler** [comment]
The label will be available again in the next release 2.0.16.35. Instead of labeling, it would be an alternative to open an own group/column for adopted children/siblings.

Similar label is planned for partners: ex-wife, fiancée, husband, etc
